image: node:24-alpine

stages:
    - build
    - publish

build-library:
    stage: build
    script:
        - npm ci
        - npm run build
    artifacts:
        paths:
            - node_modules/
            - .npm/
            - build/
        expire_in: 1 week

publish-to-npm:
    stage: publish
    dependencies:
        - build-library
    only:
        - main
    when: manual
    before_script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    script:
        - npm publish

publish-to-npm-dry-run:
    stage: publish
    dependencies:
        - build-library
    when: manual
    before_script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    script:
        - npm publish --dry-run
