export const ChannelType = {
    Email: "email",
    Telegram: "telegram",
    Web: "web",
    Facebook: "facebook",
    Vk: "vk",
    Viber: "viber",
    MobileApp: "mobile_app",
    WebWidget: "web_widget",
    MoySklad: "moy_sklad",
    Zadarma: "zadarma",
    AmoCrm: "amo_crm",
    Instagram: "instagram",
    PrivateChannel: "private_channel",
    Jira: "jira",
    Beeline: "beeline",
    ApiTelephony: "api_telephony",
    Zoom: "zoom",
    WebForm: "web_form",
    WhatsApp: "whats_app",
    Custom: "custom",
    Sms: "sms",
} as const;

export type ChannelType = typeof ChannelType[keyof typeof ChannelType];
