export enum FormFieldType {
    Unknown = "unknown",
    Text = "text",
    Money = "money",
    Number = "number",
    Date = "date",
    Time = "time",
    Checkmark = "checkmark",
    MultipleChoice = "multiple_choice",
    DueDate = "due_date",
    Email = "email",
    Phone = "phone",
    Flag = "flag",
    Step = "step",
    Status = "status",
    CreationDate = "creation_date",
    Note = "note",
    Catalog = "catalog",
    File = "file",
    Person = "person",
    Author = "author",
    Table = "table",
    Title = "title",
    Project = "project",
    FormLink = "form_link",
    DueDateTime = "due_date_time",
}
