import {Person} from "./person";
import {AttachedFile} from "./attachedFile";
import {Role} from "./role";
import {ApprovalChoice} from "../enums/approvalChoice";
import {ActivityAction} from "../enums/activityAction";
import {SmsInfo} from "./smsInfo";
import {Approval} from "./approval";
import {Channel} from "./channel";
import {FormField} from "./formFields/formField";

export type TaskComment = {
    id: number;
    text: string;
    formatted_text?: string;
    mentions?: number[];
    subject?: string;
    create_date: Date;
    author: Person;
    reassigned_to?: Person;
    field_updates?: FormField[];
    approval_choice?: ApprovalChoice;
    reset_to_step?: number;
    reply_note_id?: number;
    approvals_added?: Approval[][];
    approvals_removed?: Approval[][];
    approvals_rerequested?: Approval[][];
    subscribers_added?: Person[];
    subscribers_removed?: Person[];
    participants_added?: Person[];
    participants_removed?: Person[];
    due_date?: Date;
    due?: Date;
    scheduled_date?: Date;
    scheduled_datetime_utc?: Date;
    cancel_schedule?: boolean;
    duration?: number;
    attachments?: AttachedFile[];
    action?: ActivityAction;
    added_list_ids?: number[];
    removed_list_ids?: number[];
    approval_step?: number;
    comment_as_roles?: Role[];
    changed_step?: number;
    channel?: Channel;
    edit_comment_id?: number;
    removed_attachment_ids?: number[];
    delete_comment_id?: number;
    spent_minutes?: number;
    skip_satisfaction?: boolean;
    sms_info?: SmsInfo;
};
